### ISSUE TITLE
Panic when trying to get current user group.

### ISSUE THREAD

**Issue by kemingy** [ogham/rust-users#33]
Sorry, I'm not sure when will this happen. I found it when I'm using [lsd](https://github.com/Peltoche/lsd). Refer to the [issue](https://github.com/Peltoche/lsd/issues/48).

To test the issue, I write some test code like:
```Rust
fn main() {
    println!(
        "{:?} -> {:?}",
        get_current_username().unwrap().to_string_lossy(),
        get_current_groupname().unwrap().to_string_lossy()
    );
}
```

and get
```
Running `target/debug/rust-test`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:355:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at libstd/panicking.rs:476
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: std::panicking::try::do_call
             at libstd/panicking.rs:325
   7: core::ptr::drop_in_place
             at libcore/panicking.rs:77
   8: core::ptr::drop_in_place
             at libcore/panicking.rs:52
   9: <core::option::Option<T>>::unwrap
             at libcore/macros.rs:20
  10: rust_test::main
             at src/main.rs:5
  11: std::rt::lang_start::{{closure}}
             at libstd/rt.rs:74
  12: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  13: macho_symbol_search
             at libpanic_unwind/lib.rs:102
  14: std::alloc::default_alloc_error_hook
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  15: std::rt::lang_start
             at libstd/rt.rs:74
  16: rust_test::main
```

Not sure if this happened because of authority or VPN? I don't know how I fix this problem but it just OK after turn off and turn on VPN(one more group show up)... Very weird.

**Comment by ogham** [comment]
Hi,

I see from the other thread that you’ve already found a solution to this — the VPN was changing the group to one that was missing, so the `unwrap` failed. However, your problem encouraged me to add doctests that avoid using `unwrap`, so hopefully the return value of the functions are less confusing now.
